### ISSUE TITLE
Composer Update error 

### ISSUE THREAD

**Issue by ideadx** [j42/laravel-firebase#16]
When running composer update: 
Ambiguous class resolution, "J42\LaravelFirebase\LaravelFirebaseServiceProvider" was found in both "/Users/xx/Sites/project/vendor/j42/laravel-firebase/src/j42/LaravelFirebase/LaravelFirebaseServiceProvider.php" and "/Users/xx/Sites/project/vendor/j42/laravel-firebase/src/j42/LaravelFirebase/LaravelFirebaseServiceProvider.php", the first will be used.

**Comment by j42** [comment]
Can you give it a try now?  Let me know if it still happens—if it does (50/50) I’ll verify the psr-0 loader tomorrow and remove the classmap entries.


Also please ensure you’re using the latest version of composer with `composer self update`

**Comment by ideadx** [comment]
@j42 All good now. Thanks :)
