### ISSUE TITLE
Guzzle issue 

### ISSUE THREAD

**Issue by ideadx** [j42/laravel-firebase#18]
Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, string given.
c/Client.php on line 87 and defined
has to do with psr-7

here is code:

public function post(){

   $now = \Carbon\Carbon::now();
	
	$updatedData = [
		'id' => '1',
		'fk' => '1',
		'created_at' => $now->toDateTimeString(),
	];

	Firebase::push(Config::get('constants.update'), $updatedData);
}

**Comment by ideadx** [comment]
I think this has to do with: http://stackoverflow.com/questions/31047054/guzzle-argument-with-fail-to-recognize-as-array

**Comment by sahinyanlik** [comment]
Hi, were you able to fix the issue ?

**Comment by j42** [comment]
sorry I've been traveling and extremely busy; will resolve this evening

**Comment by ideadx** [comment]
Hi  @j42 
Any updates?

**Comment by ideadx** [comment]
@j42 if you cant resolve issues, please merge PR with guzzle 5.0 please.  This issue is causing app to brak

**Comment by j42** [comment]
sorry, I've been working on an ML project in Haskell so it's rather hard to motivate myself on anything PHP...

I'm also not using Firebase in any projects anymore, thus I'm counting on you to verify this--please give it a go, as I should have resolved dependencies and issues pertaining to Laravel 5 and Guzzle 6/PSR7.

https://github.com/j42/laravel-firebase/commit/3667896cf4dfb6f42769a070be841aed1a8504f4

**Comment by j42** [comment]
ping

**Comment by ideadx** [comment]
Thanks mate, Will try pulling and update you soon.
